//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NAVWS
{
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.2.0-preview1.23462.5")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="urn:microsoft-dynamics-schemas/codeunit/SeminarPortalIntergration", ConfigurationName="NAVWS.SeminarPortalIntergration_Port")]
    public interface SeminarPortalIntergration_Port
    {
        
        // CODEGEN: Generating message contract since the wrapper name (AddSeminarRoom_Result) of message AddSeminarRoom_Result does not match the default value (AddSeminarRoom)
        [System.ServiceModel.OperationContractAttribute(Action="urn:microsoft-dynamics-schemas/codeunit/SeminarPortalIntergration:AddSeminarRoom", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        NAVWS.AddSeminarRoom_Result AddSeminarRoom(NAVWS.AddSeminarRoom request);
        
        [System.ServiceModel.OperationContractAttribute(Action="urn:microsoft-dynamics-schemas/codeunit/SeminarPortalIntergration:AddSeminarRoom", ReplyAction="*")]
        System.Threading.Tasks.Task<NAVWS.AddSeminarRoom_Result> AddSeminarRoomAsync(NAVWS.AddSeminarRoom request);
        
        // CODEGEN: Generating message contract since the wrapper name (CreateUser_Result) of message CreateUser_Result does not match the default value (CreateUser)
        [System.ServiceModel.OperationContractAttribute(Action="urn:microsoft-dynamics-schemas/codeunit/SeminarPortalIntergration:CreateUser", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        NAVWS.CreateUser_Result CreateUser(NAVWS.CreateUser request);
        
        [System.ServiceModel.OperationContractAttribute(Action="urn:microsoft-dynamics-schemas/codeunit/SeminarPortalIntergration:CreateUser", ReplyAction="*")]
        System.Threading.Tasks.Task<NAVWS.CreateUser_Result> CreateUserAsync(NAVWS.CreateUser request);
        
        // CODEGEN: Generating message contract since the wrapper name (DeleteSeminarData_Result) of message DeleteSeminarData_Result does not match the default value (DeleteSeminarData)
        [System.ServiceModel.OperationContractAttribute(Action="urn:microsoft-dynamics-schemas/codeunit/SeminarPortalIntergration:DeleteSeminarDa" +
            "ta", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        NAVWS.DeleteSeminarData_Result DeleteSeminarData(NAVWS.DeleteSeminarData request);
        
        [System.ServiceModel.OperationContractAttribute(Action="urn:microsoft-dynamics-schemas/codeunit/SeminarPortalIntergration:DeleteSeminarDa" +
            "ta", ReplyAction="*")]
        System.Threading.Tasks.Task<NAVWS.DeleteSeminarData_Result> DeleteSeminarDataAsync(NAVWS.DeleteSeminarData request);
        
        // CODEGEN: Generating message contract since the wrapper name (DeleteSeminarRoom_Result) of message DeleteSeminarRoom_Result does not match the default value (DeleteSeminarRoom)
        [System.ServiceModel.OperationContractAttribute(Action="urn:microsoft-dynamics-schemas/codeunit/SeminarPortalIntergration:DeleteSeminarRo" +
            "om", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        NAVWS.DeleteSeminarRoom_Result DeleteSeminarRoom(NAVWS.DeleteSeminarRoom request);
        
        [System.ServiceModel.OperationContractAttribute(Action="urn:microsoft-dynamics-schemas/codeunit/SeminarPortalIntergration:DeleteSeminarRo" +
            "om", ReplyAction="*")]
        System.Threading.Tasks.Task<NAVWS.DeleteSeminarRoom_Result> DeleteSeminarRoomAsync(NAVWS.DeleteSeminarRoom request);
        
        // CODEGEN: Generating message contract since the wrapper name (GetAllSeminars_Result) of message GetAllSeminars_Result does not match the default value (GetAllSeminars)
        [System.ServiceModel.OperationContractAttribute(Action="urn:microsoft-dynamics-schemas/codeunit/SeminarPortalIntergration:GetAllSeminars", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        NAVWS.GetAllSeminars_Result GetAllSeminars(NAVWS.GetAllSeminars request);
        
        [System.ServiceModel.OperationContractAttribute(Action="urn:microsoft-dynamics-schemas/codeunit/SeminarPortalIntergration:GetAllSeminars", ReplyAction="*")]
        System.Threading.Tasks.Task<NAVWS.GetAllSeminars_Result> GetAllSeminarsAsync(NAVWS.GetAllSeminars request);
        
        // CODEGEN: Generating message contract since the wrapper name (GetSeminarData_Result) of message GetSeminarData_Result does not match the default value (GetSeminarData)
        [System.ServiceModel.OperationContractAttribute(Action="urn:microsoft-dynamics-schemas/codeunit/SeminarPortalIntergration:GetSeminarData", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        NAVWS.GetSeminarData_Result GetSeminarData(NAVWS.GetSeminarData request);
        
        [System.ServiceModel.OperationContractAttribute(Action="urn:microsoft-dynamics-schemas/codeunit/SeminarPortalIntergration:GetSeminarData", ReplyAction="*")]
        System.Threading.Tasks.Task<NAVWS.GetSeminarData_Result> GetSeminarDataAsync(NAVWS.GetSeminarData request);
        
        // CODEGEN: Generating message contract since the wrapper name (InsertSeminarData_Result) of message InsertSeminarData_Result does not match the default value (InsertSeminarData)
        [System.ServiceModel.OperationContractAttribute(Action="urn:microsoft-dynamics-schemas/codeunit/SeminarPortalIntergration:InsertSeminarDa" +
            "ta", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        NAVWS.InsertSeminarData_Result InsertSeminarData(NAVWS.InsertSeminarData request);
        
        [System.ServiceModel.OperationContractAttribute(Action="urn:microsoft-dynamics-schemas/codeunit/SeminarPortalIntergration:InsertSeminarDa" +
            "ta", ReplyAction="*")]
        System.Threading.Tasks.Task<NAVWS.InsertSeminarData_Result> InsertSeminarDataAsync(NAVWS.InsertSeminarData request);
        
        // CODEGEN: Generating message contract since the wrapper name (InsertSeminarRegData_Result) of message InsertSeminarRegData_Result does not match the default value (InsertSeminarRegData)
        [System.ServiceModel.OperationContractAttribute(Action="urn:microsoft-dynamics-schemas/codeunit/SeminarPortalIntergration:InsertSeminarRe" +
            "gData", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        NAVWS.InsertSeminarRegData_Result InsertSeminarRegData(NAVWS.InsertSeminarRegData request);
        
        [System.ServiceModel.OperationContractAttribute(Action="urn:microsoft-dynamics-schemas/codeunit/SeminarPortalIntergration:InsertSeminarRe" +
            "gData", ReplyAction="*")]
        System.Threading.Tasks.Task<NAVWS.InsertSeminarRegData_Result> InsertSeminarRegDataAsync(NAVWS.InsertSeminarRegData request);
        
        // CODEGEN: Generating message contract since the wrapper name (LoginAdmin_Result) of message LoginAdmin_Result does not match the default value (LoginAdmin)
        [System.ServiceModel.OperationContractAttribute(Action="urn:microsoft-dynamics-schemas/codeunit/SeminarPortalIntergration:LoginAdmin", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        NAVWS.LoginAdmin_Result LoginAdmin(NAVWS.LoginAdmin request);
        
        [System.ServiceModel.OperationContractAttribute(Action="urn:microsoft-dynamics-schemas/codeunit/SeminarPortalIntergration:LoginAdmin", ReplyAction="*")]
        System.Threading.Tasks.Task<NAVWS.LoginAdmin_Result> LoginAdminAsync(NAVWS.LoginAdmin request);
        
        // CODEGEN: Generating message contract since the wrapper name (LoginUser_Result) of message LoginUser_Result does not match the default value (LoginUser)
        [System.ServiceModel.OperationContractAttribute(Action="urn:microsoft-dynamics-schemas/codeunit/SeminarPortalIntergration:LoginUser", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        NAVWS.LoginUser_Result LoginUser(NAVWS.LoginUser request);
        
        [System.ServiceModel.OperationContractAttribute(Action="urn:microsoft-dynamics-schemas/codeunit/SeminarPortalIntergration:LoginUser", ReplyAction="*")]
        System.Threading.Tasks.Task<NAVWS.LoginUser_Result> LoginUserAsync(NAVWS.LoginUser request);
        
        // CODEGEN: Generating message contract since the wrapper name (RegisterAdmin_Result) of message RegisterAdmin_Result does not match the default value (RegisterAdmin)
        [System.ServiceModel.OperationContractAttribute(Action="urn:microsoft-dynamics-schemas/codeunit/SeminarPortalIntergration:RegisterAdmin", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        NAVWS.RegisterAdmin_Result RegisterAdmin(NAVWS.RegisterAdmin request);
        
        [System.ServiceModel.OperationContractAttribute(Action="urn:microsoft-dynamics-schemas/codeunit/SeminarPortalIntergration:RegisterAdmin", ReplyAction="*")]
        System.Threading.Tasks.Task<NAVWS.RegisterAdmin_Result> RegisterAdminAsync(NAVWS.RegisterAdmin request);
        
        // CODEGEN: Generating message contract since the wrapper name (RegisterParticipant_Result) of message RegisterParticipant_Result does not match the default value (RegisterParticipant)
        [System.ServiceModel.OperationContractAttribute(Action="urn:microsoft-dynamics-schemas/codeunit/SeminarPortalIntergration:RegisterPartici" +
            "pant", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        NAVWS.RegisterParticipant_Result RegisterParticipant(NAVWS.RegisterParticipant request);
        
        [System.ServiceModel.OperationContractAttribute(Action="urn:microsoft-dynamics-schemas/codeunit/SeminarPortalIntergration:RegisterPartici" +
            "pant", ReplyAction="*")]
        System.Threading.Tasks.Task<NAVWS.RegisterParticipant_Result> RegisterParticipantAsync(NAVWS.RegisterParticipant request);
        
        // CODEGEN: Generating message contract since the wrapper name (UpdateSeminarData_Result) of message UpdateSeminarData_Result does not match the default value (UpdateSeminarData)
        [System.ServiceModel.OperationContractAttribute(Action="urn:microsoft-dynamics-schemas/codeunit/SeminarPortalIntergration:UpdateSeminarDa" +
            "ta", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        NAVWS.UpdateSeminarData_Result UpdateSeminarData(NAVWS.UpdateSeminarData request);
        
        [System.ServiceModel.OperationContractAttribute(Action="urn:microsoft-dynamics-schemas/codeunit/SeminarPortalIntergration:UpdateSeminarDa" +
            "ta", ReplyAction="*")]
        System.Threading.Tasks.Task<NAVWS.UpdateSeminarData_Result> UpdateSeminarDataAsync(NAVWS.UpdateSeminarData request);
        
        // CODEGEN: Generating message contract since the wrapper name (UpdateSeminarRoom_Result) of message UpdateSeminarRoom_Result does not match the default value (UpdateSeminarRoom)
        [System.ServiceModel.OperationContractAttribute(Action="urn:microsoft-dynamics-schemas/codeunit/SeminarPortalIntergration:UpdateSeminarRo" +
            "om", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        NAVWS.UpdateSeminarRoom_Result UpdateSeminarRoom(NAVWS.UpdateSeminarRoom request);
        
        [System.ServiceModel.OperationContractAttribute(Action="urn:microsoft-dynamics-schemas/codeunit/SeminarPortalIntergration:UpdateSeminarRo" +
            "om", ReplyAction="*")]
        System.Threading.Tasks.Task<NAVWS.UpdateSeminarRoom_Result> UpdateSeminarRoomAsync(NAVWS.UpdateSeminarRoom request);
        
        // CODEGEN: Generating message contract since the wrapper name (UpdateUser_Result) of message UpdateUser_Result does not match the default value (UpdateUser)
        [System.ServiceModel.OperationContractAttribute(Action="urn:microsoft-dynamics-schemas/codeunit/SeminarPortalIntergration:UpdateUser", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        NAVWS.UpdateUser_Result UpdateUser(NAVWS.UpdateUser request);
        
        [System.ServiceModel.OperationContractAttribute(Action="urn:microsoft-dynamics-schemas/codeunit/SeminarPortalIntergration:UpdateUser", ReplyAction="*")]
        System.Threading.Tasks.Task<NAVWS.UpdateUser_Result> UpdateUserAsync(NAVWS.UpdateUser request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.2.0-preview1.23462.5")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="AddSeminarRoom", WrapperNamespace="urn:microsoft-dynamics-schemas/codeunit/SeminarPortalIntergration", IsWrapped=true)]
    public partial class AddSeminarRoom
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="urn:microsoft-dynamics-schemas/codeunit/SeminarPortalIntergration", Order=0)]
        public string name;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="urn:microsoft-dynamics-schemas/codeunit/SeminarPortalIntergration", Order=1)]
        public int maxParticipants;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="urn:microsoft-dynamics-schemas/codeunit/SeminarPortalIntergration", Order=2)]
        public bool _Internal;
        
        public AddSeminarRoom()
        {
        }
        
        public AddSeminarRoom(string name, int maxParticipants, bool _Internal)
        {
            this.name = name;
            this.maxParticipants = maxParticipants;
            this._Internal = _Internal;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.2.0-preview1.23462.5")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="AddSeminarRoom_Result", WrapperNamespace="urn:microsoft-dynamics-schemas/codeunit/SeminarPortalIntergration", IsWrapped=true)]
    public partial class AddSeminarRoom_Result
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="urn:microsoft-dynamics-schemas/codeunit/SeminarPortalIntergration", Order=0)]
        public bool return_value;
        
        public AddSeminarRoom_Result()
        {
        }
        
        public AddSeminarRoom_Result(bool return_value)
        {
            this.return_value = return_value;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.2.0-preview1.23462.5")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="CreateUser", WrapperNamespace="urn:microsoft-dynamics-schemas/codeunit/SeminarPortalIntergration", IsWrapped=true)]
    public partial class CreateUser
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="urn:microsoft-dynamics-schemas/codeunit/SeminarPortalIntergration", Order=0)]
        public string username;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="urn:microsoft-dynamics-schemas/codeunit/SeminarPortalIntergration", Order=1)]
        public string password;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="urn:microsoft-dynamics-schemas/codeunit/SeminarPortalIntergration", Order=2)]
        public string email;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="urn:microsoft-dynamics-schemas/codeunit/SeminarPortalIntergration", Order=3)]
        public string name;
        
        public CreateUser()
        {
        }
        
        public CreateUser(string username, string password, string email, string name)
        {
            this.username = username;
            this.password = password;
            this.email = email;
            this.name = name;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.2.0-preview1.23462.5")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="CreateUser_Result", WrapperNamespace="urn:microsoft-dynamics-schemas/codeunit/SeminarPortalIntergration", IsWrapped=true)]
    public partial class CreateUser_Result
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="urn:microsoft-dynamics-schemas/codeunit/SeminarPortalIntergration", Order=0)]
        public string return_value;
        
        public CreateUser_Result()
        {
        }
        
        public CreateUser_Result(string return_value)
        {
            this.return_value = return_value;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.2.0-preview1.23462.5")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="DeleteSeminarData", WrapperNamespace="urn:microsoft-dynamics-schemas/codeunit/SeminarPortalIntergration", IsWrapped=true)]
    public partial class DeleteSeminarData
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="urn:microsoft-dynamics-schemas/codeunit/SeminarPortalIntergration", Order=0)]
        public string docNo;
        
        public DeleteSeminarData()
        {
        }
        
        public DeleteSeminarData(string docNo)
        {
            this.docNo = docNo;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.2.0-preview1.23462.5")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="DeleteSeminarData_Result", WrapperNamespace="urn:microsoft-dynamics-schemas/codeunit/SeminarPortalIntergration", IsWrapped=true)]
    public partial class DeleteSeminarData_Result
    {
        
        public DeleteSeminarData_Result()
        {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.2.0-preview1.23462.5")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="DeleteSeminarRoom", WrapperNamespace="urn:microsoft-dynamics-schemas/codeunit/SeminarPortalIntergration", IsWrapped=true)]
    public partial class DeleteSeminarRoom
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="urn:microsoft-dynamics-schemas/codeunit/SeminarPortalIntergration", Order=0)]
        public string roomNo;
        
        public DeleteSeminarRoom()
        {
        }
        
        public DeleteSeminarRoom(string roomNo)
        {
            this.roomNo = roomNo;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.2.0-preview1.23462.5")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="DeleteSeminarRoom_Result", WrapperNamespace="urn:microsoft-dynamics-schemas/codeunit/SeminarPortalIntergration", IsWrapped=true)]
    public partial class DeleteSeminarRoom_Result
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="urn:microsoft-dynamics-schemas/codeunit/SeminarPortalIntergration", Order=0)]
        public bool return_value;
        
        public DeleteSeminarRoom_Result()
        {
        }
        
        public DeleteSeminarRoom_Result(bool return_value)
        {
            this.return_value = return_value;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.2.0-preview1.23462.5")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="GetAllSeminars", WrapperNamespace="urn:microsoft-dynamics-schemas/codeunit/SeminarPortalIntergration", IsWrapped=true)]
    public partial class GetAllSeminars
    {
        
        public GetAllSeminars()
        {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.2.0-preview1.23462.5")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="GetAllSeminars_Result", WrapperNamespace="urn:microsoft-dynamics-schemas/codeunit/SeminarPortalIntergration", IsWrapped=true)]
    public partial class GetAllSeminars_Result
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="urn:microsoft-dynamics-schemas/codeunit/SeminarPortalIntergration", Order=0)]
        public string return_value;
        
        public GetAllSeminars_Result()
        {
        }
        
        public GetAllSeminars_Result(string return_value)
        {
            this.return_value = return_value;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.2.0-preview1.23462.5")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="GetSeminarData", WrapperNamespace="urn:microsoft-dynamics-schemas/codeunit/SeminarPortalIntergration", IsWrapped=true)]
    public partial class GetSeminarData
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="urn:microsoft-dynamics-schemas/codeunit/SeminarPortalIntergration", Order=0)]
        public string docNo;
        
        public GetSeminarData()
        {
        }
        
        public GetSeminarData(string docNo)
        {
            this.docNo = docNo;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.2.0-preview1.23462.5")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="GetSeminarData_Result", WrapperNamespace="urn:microsoft-dynamics-schemas/codeunit/SeminarPortalIntergration", IsWrapped=true)]
    public partial class GetSeminarData_Result
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="urn:microsoft-dynamics-schemas/codeunit/SeminarPortalIntergration", Order=0)]
        public string return_value;
        
        public GetSeminarData_Result()
        {
        }
        
        public GetSeminarData_Result(string return_value)
        {
            this.return_value = return_value;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.2.0-preview1.23462.5")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="InsertSeminarData", WrapperNamespace="urn:microsoft-dynamics-schemas/codeunit/SeminarPortalIntergration", IsWrapped=true)]
    public partial class InsertSeminarData
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="urn:microsoft-dynamics-schemas/codeunit/SeminarPortalIntergration", Order=0)]
        public string name;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="urn:microsoft-dynamics-schemas/codeunit/SeminarPortalIntergration", Order=1)]
        public decimal seminar_Duration;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="urn:microsoft-dynamics-schemas/codeunit/SeminarPortalIntergration", Order=2)]
        public int minimum_Participants;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="urn:microsoft-dynamics-schemas/codeunit/SeminarPortalIntergration", Order=3)]
        public int maximum_Participants;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="urn:microsoft-dynamics-schemas/codeunit/SeminarPortalIntergration", Order=4)]
        public decimal seminar_Price;
        
        public InsertSeminarData()
        {
        }
        
        public InsertSeminarData(string name, decimal seminar_Duration, int minimum_Participants, int maximum_Participants, decimal seminar_Price)
        {
            this.name = name;
            this.seminar_Duration = seminar_Duration;
            this.minimum_Participants = minimum_Participants;
            this.maximum_Participants = maximum_Participants;
            this.seminar_Price = seminar_Price;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.2.0-preview1.23462.5")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="InsertSeminarData_Result", WrapperNamespace="urn:microsoft-dynamics-schemas/codeunit/SeminarPortalIntergration", IsWrapped=true)]
    public partial class InsertSeminarData_Result
    {
        
        public InsertSeminarData_Result()
        {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.2.0-preview1.23462.5")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="InsertSeminarRegData", WrapperNamespace="urn:microsoft-dynamics-schemas/codeunit/SeminarPortalIntergration", IsWrapped=true)]
    public partial class InsertSeminarRegData
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="urn:microsoft-dynamics-schemas/codeunit/SeminarPortalIntergration", Order=0)]
        public string seminarNo;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="urn:microsoft-dynamics-schemas/codeunit/SeminarPortalIntergration", Order=1)]
        [System.Xml.Serialization.XmlElementAttribute(DataType="date")]
        public System.DateTime startingDate;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="urn:microsoft-dynamics-schemas/codeunit/SeminarPortalIntergration", Order=2)]
        public string instructorNo;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="urn:microsoft-dynamics-schemas/codeunit/SeminarPortalIntergration", Order=3)]
        public string roomNo;
        
        public InsertSeminarRegData()
        {
        }
        
        public InsertSeminarRegData(string seminarNo, System.DateTime startingDate, string instructorNo, string roomNo)
        {
            this.seminarNo = seminarNo;
            this.startingDate = startingDate;
            this.instructorNo = instructorNo;
            this.roomNo = roomNo;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.2.0-preview1.23462.5")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="InsertSeminarRegData_Result", WrapperNamespace="urn:microsoft-dynamics-schemas/codeunit/SeminarPortalIntergration", IsWrapped=true)]
    public partial class InsertSeminarRegData_Result
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="urn:microsoft-dynamics-schemas/codeunit/SeminarPortalIntergration", Order=0)]
        public bool return_value;
        
        public InsertSeminarRegData_Result()
        {
        }
        
        public InsertSeminarRegData_Result(bool return_value)
        {
            this.return_value = return_value;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.2.0-preview1.23462.5")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="LoginAdmin", WrapperNamespace="urn:microsoft-dynamics-schemas/codeunit/SeminarPortalIntergration", IsWrapped=true)]
    public partial class LoginAdmin
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="urn:microsoft-dynamics-schemas/codeunit/SeminarPortalIntergration", Order=0)]
        public string username;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="urn:microsoft-dynamics-schemas/codeunit/SeminarPortalIntergration", Order=1)]
        public string password;
        
        public LoginAdmin()
        {
        }
        
        public LoginAdmin(string username, string password)
        {
            this.username = username;
            this.password = password;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.2.0-preview1.23462.5")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="LoginAdmin_Result", WrapperNamespace="urn:microsoft-dynamics-schemas/codeunit/SeminarPortalIntergration", IsWrapped=true)]
    public partial class LoginAdmin_Result
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="urn:microsoft-dynamics-schemas/codeunit/SeminarPortalIntergration", Order=0)]
        public string return_value;
        
        public LoginAdmin_Result()
        {
        }
        
        public LoginAdmin_Result(string return_value)
        {
            this.return_value = return_value;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.2.0-preview1.23462.5")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="LoginUser", WrapperNamespace="urn:microsoft-dynamics-schemas/codeunit/SeminarPortalIntergration", IsWrapped=true)]
    public partial class LoginUser
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="urn:microsoft-dynamics-schemas/codeunit/SeminarPortalIntergration", Order=0)]
        public string username;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="urn:microsoft-dynamics-schemas/codeunit/SeminarPortalIntergration", Order=1)]
        public string password;
        
        public LoginUser()
        {
        }
        
        public LoginUser(string username, string password)
        {
            this.username = username;
            this.password = password;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.2.0-preview1.23462.5")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="LoginUser_Result", WrapperNamespace="urn:microsoft-dynamics-schemas/codeunit/SeminarPortalIntergration", IsWrapped=true)]
    public partial class LoginUser_Result
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="urn:microsoft-dynamics-schemas/codeunit/SeminarPortalIntergration", Order=0)]
        public string return_value;
        
        public LoginUser_Result()
        {
        }
        
        public LoginUser_Result(string return_value)
        {
            this.return_value = return_value;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.2.0-preview1.23462.5")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="RegisterAdmin", WrapperNamespace="urn:microsoft-dynamics-schemas/codeunit/SeminarPortalIntergration", IsWrapped=true)]
    public partial class RegisterAdmin
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="urn:microsoft-dynamics-schemas/codeunit/SeminarPortalIntergration", Order=0)]
        public string username;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="urn:microsoft-dynamics-schemas/codeunit/SeminarPortalIntergration", Order=1)]
        public string password;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="urn:microsoft-dynamics-schemas/codeunit/SeminarPortalIntergration", Order=2)]
        public string email;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="urn:microsoft-dynamics-schemas/codeunit/SeminarPortalIntergration", Order=3)]
        public string name;
        
        public RegisterAdmin()
        {
        }
        
        public RegisterAdmin(string username, string password, string email, string name)
        {
            this.username = username;
            this.password = password;
            this.email = email;
            this.name = name;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.2.0-preview1.23462.5")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="RegisterAdmin_Result", WrapperNamespace="urn:microsoft-dynamics-schemas/codeunit/SeminarPortalIntergration", IsWrapped=true)]
    public partial class RegisterAdmin_Result
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="urn:microsoft-dynamics-schemas/codeunit/SeminarPortalIntergration", Order=0)]
        public string return_value;
        
        public RegisterAdmin_Result()
        {
        }
        
        public RegisterAdmin_Result(string return_value)
        {
            this.return_value = return_value;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.2.0-preview1.23462.5")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="RegisterParticipant", WrapperNamespace="urn:microsoft-dynamics-schemas/codeunit/SeminarPortalIntergration", IsWrapped=true)]
    public partial class RegisterParticipant
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="urn:microsoft-dynamics-schemas/codeunit/SeminarPortalIntergration", Order=0)]
        public string documentNo;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="urn:microsoft-dynamics-schemas/codeunit/SeminarPortalIntergration", Order=1)]
        public string billToCustomerNo;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="urn:microsoft-dynamics-schemas/codeunit/SeminarPortalIntergration", Order=2)]
        public string participantContactNo;
        
        public RegisterParticipant()
        {
        }
        
        public RegisterParticipant(string documentNo, string billToCustomerNo, string participantContactNo)
        {
            this.documentNo = documentNo;
            this.billToCustomerNo = billToCustomerNo;
            this.participantContactNo = participantContactNo;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.2.0-preview1.23462.5")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="RegisterParticipant_Result", WrapperNamespace="urn:microsoft-dynamics-schemas/codeunit/SeminarPortalIntergration", IsWrapped=true)]
    public partial class RegisterParticipant_Result
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="urn:microsoft-dynamics-schemas/codeunit/SeminarPortalIntergration", Order=0)]
        public bool return_value;
        
        public RegisterParticipant_Result()
        {
        }
        
        public RegisterParticipant_Result(bool return_value)
        {
            this.return_value = return_value;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.2.0-preview1.23462.5")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="UpdateSeminarData", WrapperNamespace="urn:microsoft-dynamics-schemas/codeunit/SeminarPortalIntergration", IsWrapped=true)]
    public partial class UpdateSeminarData
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="urn:microsoft-dynamics-schemas/codeunit/SeminarPortalIntergration", Order=0)]
        public string docNo;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="urn:microsoft-dynamics-schemas/codeunit/SeminarPortalIntergration", Order=1)]
        public string name;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="urn:microsoft-dynamics-schemas/codeunit/SeminarPortalIntergration", Order=2)]
        public decimal seminar_Duration;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="urn:microsoft-dynamics-schemas/codeunit/SeminarPortalIntergration", Order=3)]
        public decimal seminar_Price;
        
        public UpdateSeminarData()
        {
        }
        
        public UpdateSeminarData(string docNo, string name, decimal seminar_Duration, decimal seminar_Price)
        {
            this.docNo = docNo;
            this.name = name;
            this.seminar_Duration = seminar_Duration;
            this.seminar_Price = seminar_Price;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.2.0-preview1.23462.5")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="UpdateSeminarData_Result", WrapperNamespace="urn:microsoft-dynamics-schemas/codeunit/SeminarPortalIntergration", IsWrapped=true)]
    public partial class UpdateSeminarData_Result
    {
        
        public UpdateSeminarData_Result()
        {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.2.0-preview1.23462.5")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="UpdateSeminarRoom", WrapperNamespace="urn:microsoft-dynamics-schemas/codeunit/SeminarPortalIntergration", IsWrapped=true)]
    public partial class UpdateSeminarRoom
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="urn:microsoft-dynamics-schemas/codeunit/SeminarPortalIntergration", Order=0)]
        public string roomNo;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="urn:microsoft-dynamics-schemas/codeunit/SeminarPortalIntergration", Order=1)]
        public string name;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="urn:microsoft-dynamics-schemas/codeunit/SeminarPortalIntergration", Order=2)]
        public int maxParticipants;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="urn:microsoft-dynamics-schemas/codeunit/SeminarPortalIntergration", Order=3)]
        public bool _Internal;
        
        public UpdateSeminarRoom()
        {
        }
        
        public UpdateSeminarRoom(string roomNo, string name, int maxParticipants, bool _Internal)
        {
            this.roomNo = roomNo;
            this.name = name;
            this.maxParticipants = maxParticipants;
            this._Internal = _Internal;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.2.0-preview1.23462.5")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="UpdateSeminarRoom_Result", WrapperNamespace="urn:microsoft-dynamics-schemas/codeunit/SeminarPortalIntergration", IsWrapped=true)]
    public partial class UpdateSeminarRoom_Result
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="urn:microsoft-dynamics-schemas/codeunit/SeminarPortalIntergration", Order=0)]
        public bool return_value;
        
        public UpdateSeminarRoom_Result()
        {
        }
        
        public UpdateSeminarRoom_Result(bool return_value)
        {
            this.return_value = return_value;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.2.0-preview1.23462.5")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="UpdateUser", WrapperNamespace="urn:microsoft-dynamics-schemas/codeunit/SeminarPortalIntergration", IsWrapped=true)]
    public partial class UpdateUser
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="urn:microsoft-dynamics-schemas/codeunit/SeminarPortalIntergration", Order=0)]
        public string username;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="urn:microsoft-dynamics-schemas/codeunit/SeminarPortalIntergration", Order=1)]
        public string name;
        
        public UpdateUser()
        {
        }
        
        public UpdateUser(string username, string name)
        {
            this.username = username;
            this.name = name;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.2.0-preview1.23462.5")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="UpdateUser_Result", WrapperNamespace="urn:microsoft-dynamics-schemas/codeunit/SeminarPortalIntergration", IsWrapped=true)]
    public partial class UpdateUser_Result
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="urn:microsoft-dynamics-schemas/codeunit/SeminarPortalIntergration", Order=0)]
        public string return_value;
        
        public UpdateUser_Result()
        {
        }
        
        public UpdateUser_Result(string return_value)
        {
            this.return_value = return_value;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.2.0-preview1.23462.5")]
    public interface SeminarPortalIntergration_PortChannel : NAVWS.SeminarPortalIntergration_Port, System.ServiceModel.IClientChannel
    {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.2.0-preview1.23462.5")]
    public partial class SeminarPortalIntergration_PortClient : System.ServiceModel.ClientBase<NAVWS.SeminarPortalIntergration_Port>, NAVWS.SeminarPortalIntergration_Port
    {
        
        /// <summary>
        /// Implement this partial method to configure the service endpoint.
        /// </summary>
        /// <param name="serviceEndpoint">The endpoint to configure</param>
        /// <param name="clientCredentials">The client credentials</param>
        static partial void ConfigureEndpoint(System.ServiceModel.Description.ServiceEndpoint serviceEndpoint, System.ServiceModel.Description.ClientCredentials clientCredentials);
        
        public SeminarPortalIntergration_PortClient() : 
                base(SeminarPortalIntergration_PortClient.GetDefaultBinding(), SeminarPortalIntergration_PortClient.GetDefaultEndpointAddress())
        {
            this.Endpoint.Name = EndpointConfiguration.SeminarPortalIntergration_Port.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public SeminarPortalIntergration_PortClient(EndpointConfiguration endpointConfiguration) : 
                base(SeminarPortalIntergration_PortClient.GetBindingForEndpoint(endpointConfiguration), SeminarPortalIntergration_PortClient.GetEndpointAddress(endpointConfiguration))
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public SeminarPortalIntergration_PortClient(EndpointConfiguration endpointConfiguration, string remoteAddress) : 
                base(SeminarPortalIntergration_PortClient.GetBindingForEndpoint(endpointConfiguration), new System.ServiceModel.EndpointAddress(remoteAddress))
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public SeminarPortalIntergration_PortClient(EndpointConfiguration endpointConfiguration, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(SeminarPortalIntergration_PortClient.GetBindingForEndpoint(endpointConfiguration), remoteAddress)
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public SeminarPortalIntergration_PortClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress)
        {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        NAVWS.AddSeminarRoom_Result NAVWS.SeminarPortalIntergration_Port.AddSeminarRoom(NAVWS.AddSeminarRoom request)
        {
            return base.Channel.AddSeminarRoom(request);
        }
        
        public bool AddSeminarRoom(string name, int maxParticipants, bool _Internal)
        {
            NAVWS.AddSeminarRoom inValue = new NAVWS.AddSeminarRoom();
            inValue.name = name;
            inValue.maxParticipants = maxParticipants;
            inValue._Internal = _Internal;
            NAVWS.AddSeminarRoom_Result retVal = ((NAVWS.SeminarPortalIntergration_Port)(this)).AddSeminarRoom(inValue);
            return retVal.return_value;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<NAVWS.AddSeminarRoom_Result> NAVWS.SeminarPortalIntergration_Port.AddSeminarRoomAsync(NAVWS.AddSeminarRoom request)
        {
            return base.Channel.AddSeminarRoomAsync(request);
        }
        
        public System.Threading.Tasks.Task<NAVWS.AddSeminarRoom_Result> AddSeminarRoomAsync(string name, int maxParticipants, bool _Internal)
        {
            NAVWS.AddSeminarRoom inValue = new NAVWS.AddSeminarRoom();
            inValue.name = name;
            inValue.maxParticipants = maxParticipants;
            inValue._Internal = _Internal;
            return ((NAVWS.SeminarPortalIntergration_Port)(this)).AddSeminarRoomAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        NAVWS.CreateUser_Result NAVWS.SeminarPortalIntergration_Port.CreateUser(NAVWS.CreateUser request)
        {
            return base.Channel.CreateUser(request);
        }
        
        public string CreateUser(string username, string password, string email, string name)
        {
            NAVWS.CreateUser inValue = new NAVWS.CreateUser();
            inValue.username = username;
            inValue.password = password;
            inValue.email = email;
            inValue.name = name;
            NAVWS.CreateUser_Result retVal = ((NAVWS.SeminarPortalIntergration_Port)(this)).CreateUser(inValue);
            return retVal.return_value;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<NAVWS.CreateUser_Result> NAVWS.SeminarPortalIntergration_Port.CreateUserAsync(NAVWS.CreateUser request)
        {
            return base.Channel.CreateUserAsync(request);
        }
        
        public System.Threading.Tasks.Task<NAVWS.CreateUser_Result> CreateUserAsync(string username, string password, string email, string name)
        {
            NAVWS.CreateUser inValue = new NAVWS.CreateUser();
            inValue.username = username;
            inValue.password = password;
            inValue.email = email;
            inValue.name = name;
            return ((NAVWS.SeminarPortalIntergration_Port)(this)).CreateUserAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        NAVWS.DeleteSeminarData_Result NAVWS.SeminarPortalIntergration_Port.DeleteSeminarData(NAVWS.DeleteSeminarData request)
        {
            return base.Channel.DeleteSeminarData(request);
        }
        
        public void DeleteSeminarData(string docNo)
        {
            NAVWS.DeleteSeminarData inValue = new NAVWS.DeleteSeminarData();
            inValue.docNo = docNo;
            NAVWS.DeleteSeminarData_Result retVal = ((NAVWS.SeminarPortalIntergration_Port)(this)).DeleteSeminarData(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<NAVWS.DeleteSeminarData_Result> NAVWS.SeminarPortalIntergration_Port.DeleteSeminarDataAsync(NAVWS.DeleteSeminarData request)
        {
            return base.Channel.DeleteSeminarDataAsync(request);
        }
        
        public System.Threading.Tasks.Task<NAVWS.DeleteSeminarData_Result> DeleteSeminarDataAsync(string docNo)
        {
            NAVWS.DeleteSeminarData inValue = new NAVWS.DeleteSeminarData();
            inValue.docNo = docNo;
            return ((NAVWS.SeminarPortalIntergration_Port)(this)).DeleteSeminarDataAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        NAVWS.DeleteSeminarRoom_Result NAVWS.SeminarPortalIntergration_Port.DeleteSeminarRoom(NAVWS.DeleteSeminarRoom request)
        {
            return base.Channel.DeleteSeminarRoom(request);
        }
        
        public bool DeleteSeminarRoom(string roomNo)
        {
            NAVWS.DeleteSeminarRoom inValue = new NAVWS.DeleteSeminarRoom();
            inValue.roomNo = roomNo;
            NAVWS.DeleteSeminarRoom_Result retVal = ((NAVWS.SeminarPortalIntergration_Port)(this)).DeleteSeminarRoom(inValue);
            return retVal.return_value;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<NAVWS.DeleteSeminarRoom_Result> NAVWS.SeminarPortalIntergration_Port.DeleteSeminarRoomAsync(NAVWS.DeleteSeminarRoom request)
        {
            return base.Channel.DeleteSeminarRoomAsync(request);
        }
        
        public System.Threading.Tasks.Task<NAVWS.DeleteSeminarRoom_Result> DeleteSeminarRoomAsync(string roomNo)
        {
            NAVWS.DeleteSeminarRoom inValue = new NAVWS.DeleteSeminarRoom();
            inValue.roomNo = roomNo;
            return ((NAVWS.SeminarPortalIntergration_Port)(this)).DeleteSeminarRoomAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        NAVWS.GetAllSeminars_Result NAVWS.SeminarPortalIntergration_Port.GetAllSeminars(NAVWS.GetAllSeminars request)
        {
            return base.Channel.GetAllSeminars(request);
        }
        
        public string GetAllSeminars()
        {
            NAVWS.GetAllSeminars inValue = new NAVWS.GetAllSeminars();
            NAVWS.GetAllSeminars_Result retVal = ((NAVWS.SeminarPortalIntergration_Port)(this)).GetAllSeminars(inValue);
            return retVal.return_value;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<NAVWS.GetAllSeminars_Result> NAVWS.SeminarPortalIntergration_Port.GetAllSeminarsAsync(NAVWS.GetAllSeminars request)
        {
            return base.Channel.GetAllSeminarsAsync(request);
        }
        
        public System.Threading.Tasks.Task<NAVWS.GetAllSeminars_Result> GetAllSeminarsAsync()
        {
            NAVWS.GetAllSeminars inValue = new NAVWS.GetAllSeminars();
            return ((NAVWS.SeminarPortalIntergration_Port)(this)).GetAllSeminarsAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        NAVWS.GetSeminarData_Result NAVWS.SeminarPortalIntergration_Port.GetSeminarData(NAVWS.GetSeminarData request)
        {
            return base.Channel.GetSeminarData(request);
        }
        
        public string GetSeminarData(string docNo)
        {
            NAVWS.GetSeminarData inValue = new NAVWS.GetSeminarData();
            inValue.docNo = docNo;
            NAVWS.GetSeminarData_Result retVal = ((NAVWS.SeminarPortalIntergration_Port)(this)).GetSeminarData(inValue);
            return retVal.return_value;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<NAVWS.GetSeminarData_Result> NAVWS.SeminarPortalIntergration_Port.GetSeminarDataAsync(NAVWS.GetSeminarData request)
        {
            return base.Channel.GetSeminarDataAsync(request);
        }
        
        public System.Threading.Tasks.Task<NAVWS.GetSeminarData_Result> GetSeminarDataAsync(string docNo)
        {
            NAVWS.GetSeminarData inValue = new NAVWS.GetSeminarData();
            inValue.docNo = docNo;
            return ((NAVWS.SeminarPortalIntergration_Port)(this)).GetSeminarDataAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        NAVWS.InsertSeminarData_Result NAVWS.SeminarPortalIntergration_Port.InsertSeminarData(NAVWS.InsertSeminarData request)
        {
            return base.Channel.InsertSeminarData(request);
        }
        
        public void InsertSeminarData(string name, decimal seminar_Duration, int minimum_Participants, int maximum_Participants, decimal seminar_Price)
        {
            NAVWS.InsertSeminarData inValue = new NAVWS.InsertSeminarData();
            inValue.name = name;
            inValue.seminar_Duration = seminar_Duration;
            inValue.minimum_Participants = minimum_Participants;
            inValue.maximum_Participants = maximum_Participants;
            inValue.seminar_Price = seminar_Price;
            NAVWS.InsertSeminarData_Result retVal = ((NAVWS.SeminarPortalIntergration_Port)(this)).InsertSeminarData(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<NAVWS.InsertSeminarData_Result> NAVWS.SeminarPortalIntergration_Port.InsertSeminarDataAsync(NAVWS.InsertSeminarData request)
        {
            return base.Channel.InsertSeminarDataAsync(request);
        }
        
        public System.Threading.Tasks.Task<NAVWS.InsertSeminarData_Result> InsertSeminarDataAsync(string name, decimal seminar_Duration, int minimum_Participants, int maximum_Participants, decimal seminar_Price)
        {
            NAVWS.InsertSeminarData inValue = new NAVWS.InsertSeminarData();
            inValue.name = name;
            inValue.seminar_Duration = seminar_Duration;
            inValue.minimum_Participants = minimum_Participants;
            inValue.maximum_Participants = maximum_Participants;
            inValue.seminar_Price = seminar_Price;
            return ((NAVWS.SeminarPortalIntergration_Port)(this)).InsertSeminarDataAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        NAVWS.InsertSeminarRegData_Result NAVWS.SeminarPortalIntergration_Port.InsertSeminarRegData(NAVWS.InsertSeminarRegData request)
        {
            return base.Channel.InsertSeminarRegData(request);
        }
        
        public bool InsertSeminarRegData(string seminarNo, System.DateTime startingDate, string instructorNo, string roomNo)
        {
            NAVWS.InsertSeminarRegData inValue = new NAVWS.InsertSeminarRegData();
            inValue.seminarNo = seminarNo;
            inValue.startingDate = startingDate;
            inValue.instructorNo = instructorNo;
            inValue.roomNo = roomNo;
            NAVWS.InsertSeminarRegData_Result retVal = ((NAVWS.SeminarPortalIntergration_Port)(this)).InsertSeminarRegData(inValue);
            return retVal.return_value;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<NAVWS.InsertSeminarRegData_Result> NAVWS.SeminarPortalIntergration_Port.InsertSeminarRegDataAsync(NAVWS.InsertSeminarRegData request)
        {
            return base.Channel.InsertSeminarRegDataAsync(request);
        }
        
        public System.Threading.Tasks.Task<NAVWS.InsertSeminarRegData_Result> InsertSeminarRegDataAsync(string seminarNo, System.DateTime startingDate, string instructorNo, string roomNo)
        {
            NAVWS.InsertSeminarRegData inValue = new NAVWS.InsertSeminarRegData();
            inValue.seminarNo = seminarNo;
            inValue.startingDate = startingDate;
            inValue.instructorNo = instructorNo;
            inValue.roomNo = roomNo;
            return ((NAVWS.SeminarPortalIntergration_Port)(this)).InsertSeminarRegDataAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        NAVWS.LoginAdmin_Result NAVWS.SeminarPortalIntergration_Port.LoginAdmin(NAVWS.LoginAdmin request)
        {
            return base.Channel.LoginAdmin(request);
        }
        
        public string LoginAdmin(string username, string password)
        {
            NAVWS.LoginAdmin inValue = new NAVWS.LoginAdmin();
            inValue.username = username;
            inValue.password = password;
            NAVWS.LoginAdmin_Result retVal = ((NAVWS.SeminarPortalIntergration_Port)(this)).LoginAdmin(inValue);
            return retVal.return_value;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<NAVWS.LoginAdmin_Result> NAVWS.SeminarPortalIntergration_Port.LoginAdminAsync(NAVWS.LoginAdmin request)
        {
            return base.Channel.LoginAdminAsync(request);
        }
        
        public System.Threading.Tasks.Task<NAVWS.LoginAdmin_Result> LoginAdminAsync(string username, string password)
        {
            NAVWS.LoginAdmin inValue = new NAVWS.LoginAdmin();
            inValue.username = username;
            inValue.password = password;
            return ((NAVWS.SeminarPortalIntergration_Port)(this)).LoginAdminAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        NAVWS.LoginUser_Result NAVWS.SeminarPortalIntergration_Port.LoginUser(NAVWS.LoginUser request)
        {
            return base.Channel.LoginUser(request);
        }
        
        public string LoginUser(string username, string password)
        {
            NAVWS.LoginUser inValue = new NAVWS.LoginUser();
            inValue.username = username;
            inValue.password = password;
            NAVWS.LoginUser_Result retVal = ((NAVWS.SeminarPortalIntergration_Port)(this)).LoginUser(inValue);
            return retVal.return_value;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<NAVWS.LoginUser_Result> NAVWS.SeminarPortalIntergration_Port.LoginUserAsync(NAVWS.LoginUser request)
        {
            return base.Channel.LoginUserAsync(request);
        }
        
        public System.Threading.Tasks.Task<NAVWS.LoginUser_Result> LoginUserAsync(string username, string password)
        {
            NAVWS.LoginUser inValue = new NAVWS.LoginUser();
            inValue.username = username;
            inValue.password = password;
            return ((NAVWS.SeminarPortalIntergration_Port)(this)).LoginUserAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        NAVWS.RegisterAdmin_Result NAVWS.SeminarPortalIntergration_Port.RegisterAdmin(NAVWS.RegisterAdmin request)
        {
            return base.Channel.RegisterAdmin(request);
        }
        
        public string RegisterAdmin(string username, string password, string email, string name)
        {
            NAVWS.RegisterAdmin inValue = new NAVWS.RegisterAdmin();
            inValue.username = username;
            inValue.password = password;
            inValue.email = email;
            inValue.name = name;
            NAVWS.RegisterAdmin_Result retVal = ((NAVWS.SeminarPortalIntergration_Port)(this)).RegisterAdmin(inValue);
            return retVal.return_value;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<NAVWS.RegisterAdmin_Result> NAVWS.SeminarPortalIntergration_Port.RegisterAdminAsync(NAVWS.RegisterAdmin request)
        {
            return base.Channel.RegisterAdminAsync(request);
        }
        
        public System.Threading.Tasks.Task<NAVWS.RegisterAdmin_Result> RegisterAdminAsync(string username, string password, string email, string name)
        {
            NAVWS.RegisterAdmin inValue = new NAVWS.RegisterAdmin();
            inValue.username = username;
            inValue.password = password;
            inValue.email = email;
            inValue.name = name;
            return ((NAVWS.SeminarPortalIntergration_Port)(this)).RegisterAdminAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        NAVWS.RegisterParticipant_Result NAVWS.SeminarPortalIntergration_Port.RegisterParticipant(NAVWS.RegisterParticipant request)
        {
            return base.Channel.RegisterParticipant(request);
        }
        
        public bool RegisterParticipant(string documentNo, string billToCustomerNo, string participantContactNo)
        {
            NAVWS.RegisterParticipant inValue = new NAVWS.RegisterParticipant();
            inValue.documentNo = documentNo;
            inValue.billToCustomerNo = billToCustomerNo;
            inValue.participantContactNo = participantContactNo;
            NAVWS.RegisterParticipant_Result retVal = ((NAVWS.SeminarPortalIntergration_Port)(this)).RegisterParticipant(inValue);
            return retVal.return_value;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<NAVWS.RegisterParticipant_Result> NAVWS.SeminarPortalIntergration_Port.RegisterParticipantAsync(NAVWS.RegisterParticipant request)
        {
            return base.Channel.RegisterParticipantAsync(request);
        }
        
        public System.Threading.Tasks.Task<NAVWS.RegisterParticipant_Result> RegisterParticipantAsync(string documentNo, string billToCustomerNo, string participantContactNo)
        {
            NAVWS.RegisterParticipant inValue = new NAVWS.RegisterParticipant();
            inValue.documentNo = documentNo;
            inValue.billToCustomerNo = billToCustomerNo;
            inValue.participantContactNo = participantContactNo;
            return ((NAVWS.SeminarPortalIntergration_Port)(this)).RegisterParticipantAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        NAVWS.UpdateSeminarData_Result NAVWS.SeminarPortalIntergration_Port.UpdateSeminarData(NAVWS.UpdateSeminarData request)
        {
            return base.Channel.UpdateSeminarData(request);
        }
        
        public void UpdateSeminarData(string docNo, string name, decimal seminar_Duration, decimal seminar_Price)
        {
            NAVWS.UpdateSeminarData inValue = new NAVWS.UpdateSeminarData();
            inValue.docNo = docNo;
            inValue.name = name;
            inValue.seminar_Duration = seminar_Duration;
            inValue.seminar_Price = seminar_Price;
            NAVWS.UpdateSeminarData_Result retVal = ((NAVWS.SeminarPortalIntergration_Port)(this)).UpdateSeminarData(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<NAVWS.UpdateSeminarData_Result> NAVWS.SeminarPortalIntergration_Port.UpdateSeminarDataAsync(NAVWS.UpdateSeminarData request)
        {
            return base.Channel.UpdateSeminarDataAsync(request);
        }
        
        public System.Threading.Tasks.Task<NAVWS.UpdateSeminarData_Result> UpdateSeminarDataAsync(string docNo, string name, decimal seminar_Duration, decimal seminar_Price)
        {
            NAVWS.UpdateSeminarData inValue = new NAVWS.UpdateSeminarData();
            inValue.docNo = docNo;
            inValue.name = name;
            inValue.seminar_Duration = seminar_Duration;
            inValue.seminar_Price = seminar_Price;
            return ((NAVWS.SeminarPortalIntergration_Port)(this)).UpdateSeminarDataAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        NAVWS.UpdateSeminarRoom_Result NAVWS.SeminarPortalIntergration_Port.UpdateSeminarRoom(NAVWS.UpdateSeminarRoom request)
        {
            return base.Channel.UpdateSeminarRoom(request);
        }
        
        public bool UpdateSeminarRoom(string roomNo, string name, int maxParticipants, bool _Internal)
        {
            NAVWS.UpdateSeminarRoom inValue = new NAVWS.UpdateSeminarRoom();
            inValue.roomNo = roomNo;
            inValue.name = name;
            inValue.maxParticipants = maxParticipants;
            inValue._Internal = _Internal;
            NAVWS.UpdateSeminarRoom_Result retVal = ((NAVWS.SeminarPortalIntergration_Port)(this)).UpdateSeminarRoom(inValue);
            return retVal.return_value;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<NAVWS.UpdateSeminarRoom_Result> NAVWS.SeminarPortalIntergration_Port.UpdateSeminarRoomAsync(NAVWS.UpdateSeminarRoom request)
        {
            return base.Channel.UpdateSeminarRoomAsync(request);
        }
        
        public System.Threading.Tasks.Task<NAVWS.UpdateSeminarRoom_Result> UpdateSeminarRoomAsync(string roomNo, string name, int maxParticipants, bool _Internal)
        {
            NAVWS.UpdateSeminarRoom inValue = new NAVWS.UpdateSeminarRoom();
            inValue.roomNo = roomNo;
            inValue.name = name;
            inValue.maxParticipants = maxParticipants;
            inValue._Internal = _Internal;
            return ((NAVWS.SeminarPortalIntergration_Port)(this)).UpdateSeminarRoomAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        NAVWS.UpdateUser_Result NAVWS.SeminarPortalIntergration_Port.UpdateUser(NAVWS.UpdateUser request)
        {
            return base.Channel.UpdateUser(request);
        }
        
        public string UpdateUser(string username, string name)
        {
            NAVWS.UpdateUser inValue = new NAVWS.UpdateUser();
            inValue.username = username;
            inValue.name = name;
            NAVWS.UpdateUser_Result retVal = ((NAVWS.SeminarPortalIntergration_Port)(this)).UpdateUser(inValue);
            return retVal.return_value;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<NAVWS.UpdateUser_Result> NAVWS.SeminarPortalIntergration_Port.UpdateUserAsync(NAVWS.UpdateUser request)
        {
            return base.Channel.UpdateUserAsync(request);
        }
        
        public System.Threading.Tasks.Task<NAVWS.UpdateUser_Result> UpdateUserAsync(string username, string name)
        {
            NAVWS.UpdateUser inValue = new NAVWS.UpdateUser();
            inValue.username = username;
            inValue.name = name;
            return ((NAVWS.SeminarPortalIntergration_Port)(this)).UpdateUserAsync(inValue);
        }
        
        public virtual System.Threading.Tasks.Task OpenAsync()
        {
            return System.Threading.Tasks.Task.Factory.FromAsync(((System.ServiceModel.ICommunicationObject)(this)).BeginOpen(null, null), new System.Action<System.IAsyncResult>(((System.ServiceModel.ICommunicationObject)(this)).EndOpen));
        }
        
        private static System.ServiceModel.Channels.Binding GetBindingForEndpoint(EndpointConfiguration endpointConfiguration)
        {
            if ((endpointConfiguration == EndpointConfiguration.SeminarPortalIntergration_Port))
            {
                System.ServiceModel.BasicHttpBinding result = new System.ServiceModel.BasicHttpBinding();
                result.MaxBufferSize = int.MaxValue;
                result.ReaderQuotas = System.Xml.XmlDictionaryReaderQuotas.Max;
                result.MaxReceivedMessageSize = int.MaxValue;
                result.AllowCookies = true;
                return result;
            }
            throw new System.InvalidOperationException(string.Format("Could not find endpoint with name \'{0}\'.", endpointConfiguration));
        }
        
        private static System.ServiceModel.EndpointAddress GetEndpointAddress(EndpointConfiguration endpointConfiguration)
        {
            if ((endpointConfiguration == EndpointConfiguration.SeminarPortalIntergration_Port))
            {
                return new System.ServiceModel.EndpointAddress("http://desktop-eq55q8h:7047/BC240/WS/CRONUS International Ltd./Codeunit/SeminarPo" +
                        "rtalIntergration");
            }
            throw new System.InvalidOperationException(string.Format("Could not find endpoint with name \'{0}\'.", endpointConfiguration));
        }
        
        private static System.ServiceModel.Channels.Binding GetDefaultBinding()
        {
            return SeminarPortalIntergration_PortClient.GetBindingForEndpoint(EndpointConfiguration.SeminarPortalIntergration_Port);
        }
        
        private static System.ServiceModel.EndpointAddress GetDefaultEndpointAddress()
        {
            return SeminarPortalIntergration_PortClient.GetEndpointAddress(EndpointConfiguration.SeminarPortalIntergration_Port);
        }
        
        public enum EndpointConfiguration
        {
            
            SeminarPortalIntergration_Port,
        }
    }
}
